"""Generate smoke-test configurations from production configs.

Reads each production train/backtest config and writes a ``smoke-`` prefixed
variant with reduced iterations, fewer seeds, and a shorter test window.
Existing smoke configs are overwritten so they stay in sync with production.

Usage::

    python scripts/generate_smoke_configs.py          # generate all
    python scripts/generate_smoke_configs.py --dry-run # preview without writing
"""

import argparse
import os
import sys

import yaml

CONFIGS_DIR = os.path.join(os.path.dirname(__file__), os.pardir, "configs")
TRAIN_DIR = os.path.join(CONFIGS_DIR, "train_settings")
BACKTEST_DIR = os.path.join(CONFIGS_DIR, "backtest_settings")

SMOKE_TRAIN_OVERRIDES = {
    "random_search_max_iterations": 5,
    "top_n_seeds": 5,
    "first_test_year": 2020,
    "test_start_years": [2020],
}

SMOKE_BACKTEST_TOP_N = 5

DL_BACKTEST_MODULE = "deepm.backtest.models.deep_momentum"


def _write_yaml(path: str, data: dict, *, dry_run: bool = False) -> None:
    header = "# AUTO-GENERATED by generate_smoke_configs.py — do not edit manually.\n"
    if dry_run:
        print(f"  [dry-run] would write {path}")
        return
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(data, f, default_flow_style=False, sort_keys=False)


def generate_smoke_train_configs(*, dry_run: bool = False) -> list[str]:
    """Return list of generated smoke train config names (without .yaml)."""
    generated = []
    for fname in sorted(os.listdir(TRAIN_DIR)):
        if not fname.endswith(".yaml") or fname.startswith("smoke-"):
            continue
        src = os.path.join(TRAIN_DIR, fname)
        with open(src, encoding="utf-8") as f:
            cfg = yaml.safe_load(f)
        cfg.update(SMOKE_TRAIN_OVERRIDES)
        dst_name = f"smoke-{fname}"
        dst = os.path.join(TRAIN_DIR, dst_name)
        _write_yaml(dst, cfg, dry_run=dry_run)
        generated.append(dst_name.replace(".yaml", ""))
    return generated


def generate_smoke_backtest_configs(*, dry_run: bool = False) -> list[str]:
    """Return list of generated smoke backtest config names (without .yaml)."""
    generated = []
    for fname in sorted(os.listdir(BACKTEST_DIR)):
        if not fname.endswith(".yaml"):
            continue
        if fname.startswith("bt-smoke-") or fname.startswith("bt-post2020-"):
            continue
        # Only create smoke variants for DL model backtests and seed variants
        src = os.path.join(BACKTEST_DIR, fname)
        with open(src, encoding="utf-8") as f:
            cfg = yaml.safe_load(f)
        model = cfg.get("model", {})
        if model.get("module") != DL_BACKTEST_MODULE:
            continue
        # Skip seed-ablation configs (e.g. bt-deepm-gat-1seed)
        base = fname.replace(".yaml", "")
        if any(base.endswith(f"-{n}seed") for n in ("1", "10", "50", "100")):
            continue

        original_train_yaml = model["train_yaml"]
        model["train_yaml"] = f"smoke-{original_train_yaml}"
        model["top_n_seeds"] = SMOKE_BACKTEST_TOP_N
        dst_name = fname.replace("bt-", "bt-smoke-", 1)
        dst = os.path.join(BACKTEST_DIR, dst_name)
        _write_yaml(dst, cfg, dry_run=dry_run)
        generated.append(dst_name.replace(".yaml", ""))
    return generated


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true", help="Preview without writing files"
    )
    args = parser.parse_args()

    print("Generating smoke train configs …")
    train_cfgs = generate_smoke_train_configs(dry_run=args.dry_run)
    print(f"  {len(train_cfgs)} configs")

    print("Generating smoke backtest configs …")
    bt_cfgs = generate_smoke_backtest_configs(dry_run=args.dry_run)
    print(f"  {len(bt_cfgs)} configs")

    if not args.dry_run:
        print("Done.")


if __name__ == "__main__":
    main()
